### ISSUE TITLE
12/29 Migration Fails on Install With Older Data/Schema

### ISSUE THREAD

**Issue by deirdresm** [swarfarm/swarfarm#197]
I don't think this is related to the bestiary_data.json not being updated in the repository as the relevant GameItem exists in that file.

I tried this on:

1. Existing Vagrant/Virtualbox install (that I've had for a year-ish)
2. Fresh install attempt (direct, by hand) on macOS High Sierra.
3. New Vagrant/Virtualbox install.

Same result.

The issue is line 15 of https://github.com/PeteAndersen/swarfarm/blob/master/herders/migrations/0021_auto_20201229_1608.py

…as that query fails.

It's obviously in the bestiary data:

```
  {
    "model": "bestiary.gameitem",
    "pk": 12,
    "fields": {
      "com2us_id": 11001,
      "category": 11,
      "name": "Water Low Essence",
      "icon": "essence_water_low.png",
      "description": "",
      "slug": "water-low-essence",
      "sell_value": null
    }
  },
```

…but we also need to ensure migrations work on an initial install, as data loading comes *after* migrations (e.g., how deployment_assets/run_initial_setup.sh specifies).

```
echo "Running database migrations..."
python manage.py migrate

echo "Loading initial data..."
python manage.py loaddata bestiary_data
python manage.py loaddata initial_auth_groups
```

Anyhow, here's the error. I'm puzzled why I received it on a November-era data model (to the current bestiary_data.json) that has those fields and provably has that record loaded.

```
    default: Traceback (most recent call last):
    default:   File "manage.py", line 12, in <module>
    default:     execute_from_command_line(sys.argv)
    default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.8/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    default:     utility.execute()
    default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.8/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    default:     self.fetch_command(subcommand).run_from_argv(self.argv)
    default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.8/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    default:     self.execute(*args, **cmd_options)
    default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.8/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    default:     output = self.handle(*args, **options)
    default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.8/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    default:     res = handle_func(*args, **kwargs)
    default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.8/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    default:     fake_initial=fake_initial,
    default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.8/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    default:     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
    default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.8/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    default:     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
    default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.8/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    default:     state = migration.apply(state, schema_editor)
    default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.8/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    default:     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
    default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.8/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    default:     self.code(from_state.apps, schema_editor)
    default:   File "/vagrant/herders/migrations/0021_auto_20201229_1608.py", line 15, in populate_new_storage
    default:     GameItem.objects.get(category=11, com2us_id=11001).pk,
    default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.8/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    default:     return getattr(self.get_queryset(), name)(*args, **kwargs)
    default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.8/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    default:     self.model._meta.object_name
    default: __fake__.DoesNotExist: GameItem matching query does not exist.
```

<img width="657" alt="Screen Shot 2021-01-20 at 17 11 20" src="https://user-images.githubusercontent.com/10251429/105264884-92481280-5b45-11eb-9c3b-b8a852764f84.png">

**Comment by QuatZo** [comment]
I've reported it to Porksmash some time ago (along other things, so he could forget).
Basically, you just need to run migrations one more time and everything works as it should. The problem is, it's trying to get stuff that not yet exists in database, since Bestiary Init load is being done after migrations.

It's a workaround, of course.

**Comment by deirdresm** [comment]
Gotcha. I finished the process by hand (from the provision.sh) and it worked okay.

I figured out why it was failing, just not exactly what I needed to do to resolve it. Got that taken care of, but perhaps should leave this open as a reminder. :P
