### ISSUE TITLE
Loading fixtures of bestiary data fails

### ISSUE THREAD

**Issue by Azd325** [swarfarm/swarfarm#70]
```
==> default: Loading initial bestiary data...
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.1/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
==> default:     return self.cursor.execute(sql, params)
==> default: psycopg2.IntegrityError: null value in column "hits" violates not-null constraint
==> default: DETAIL:  Failing row contains (1, Forbidden Ingredient (Passive), Increases the Skill Level of the monster by 1 when used as Power..., 1, , skill_icon_0006_0_1.png, 1, t, null, 99004, null, f, , []).
==> default:
==> default:
==> default: The above exception was the direct cause of the following exception:
==> default:
==> default: Traceback (most recent call last):
==> default:   File "manage.py", line 12, in <module>
==> default:     execute_from_command_line(sys.argv)
==> default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.1/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
==> default:     utility.execute()
==> default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.1/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
==> default:     self.fetch_command(subcommand).run_from_argv(self.argv)
==> default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.1/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
==> default:     self.execute(*args, **cmd_options)
==> default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.1/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
==> default:     output = self.handle(*args, **options)
==> default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.1/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 69, in handle
==> default:     self.loaddata(fixture_labels)
==> default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.1/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 109, in loaddata
==> default:     self.load_label(fixture_label)
==> default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.1/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 175, in load_label
==> default:     obj.save(using=self.using)
==> default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.1/lib/python3.6/site-packages/django/core/serializers/base.py", line 205, in save
==> default:     models.Model.save_base(self.object, using=using, raw=True, **kwargs)
==> default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.1/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
==> default:     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
==> default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.1/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
==> default:     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
==> default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.1/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
==> default:     using=using, raw=raw)
==> default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.1/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
==> default:     return getattr(self.get_queryset(), name)(*args, **kwargs)
==> default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.1/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert
==> default:     return query.get_compiler(using=using).execute_sql(return_id)
==> default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.1/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
==> default:     cursor.execute(sql, params)
==> default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.1/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in execute
==> default:     return super(CursorDebugWrapper, self).execute(sql, params)
==> default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.1/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
==> default:     return self.cursor.execute(sql, params)
==> default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.1/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
==> default:     six.reraise(dj_exc_type, dj_exc_value, traceback)
==> default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.1/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
==> default:     raise value.with_traceback(tb)
==> default:   File "/home/vagrant/.pyenv/versions/swarfarm-3.6.1/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
==> default:     return self.cursor.execute(sql, params)
==> default: django.db.utils.IntegrityError: Problem installing fixture '/vagrant/herders/fixtures/bestiary_data.json': Could not load herders.MonsterSkill(pk=1): null value in column "hits" violates not-null constraint
==> default: DETAIL:  Failing row contains (1, Forbidden Ingredient (Passive), Increases the Skill Level of the monster by 1 when used as Power..., 1, , skill_icon_0006_0_1.png, 1, t, null, 99004, null, f, , []).
```

**Comment by PeteAndersen** [comment]
Thanks, I've updated the fixture so it is compatible. I recently changed that field to non-nullable.

**Comment by Azd325** [comment]
Cool, thanks.
